---
title: "README"
author: "Jon Clucas"
date: "2/24/2017"
output: md_document
---

```{r, include=FALSE}
# load libraries
require(tidyr)
require(dplyr)
require(ggplot2)
require(svglite)
# load data
# specify filepath to csv
fp <- "/Volumes/Data/Research/CDB/openSMILE/adults_speak/adults_speak.csv"
# read csv into `adults` variable as Boolean matrix
adults <- gather(read.csv(fp, header = TRUE, colClasses =
          c(NA, "logical", "logical", "logical", "logical", "logical")),
          cond, adults_speaking, -c(X, SM.dx))
# remove `fp` variable
remove(fp)

# reshape data
colnames(adults)[1] = "URSI"
adults = separate(data=adults, col=cond, into=c("vocal", "stranger"), remove=TRUE)
adults["stranger"] = adults["stranger"] == "w"
adults["vocal"] = adults["vocal"] == "vocal"
```

```{r}
summary(aov(SM.dx ~ adults_speaking + Error(URSI), data=adults))
```

```{r}
summary(aov(vocal ~ adults_speaking + Error(URSI), data=adults))
```

```{r}
summary(aov(stranger ~ adults_speaking + Error(URSI), data=adults))
```

```{r}
summary(aov(SM.dx ~ (vocal * stranger * adults_speaking) + Error(URSI), data=adults))
```

```{r}
summary(aov(adults_speaking ~ (vocal * stranger * SM.dx) + Error(URSI), data=adults))
```

```{r}
adults %>%
  group_by(stranger, vocal) %>%
  filter(adults_speaking == TRUE) %>%
  ggplot(aes(x=factor(vocal, labels=c("button press", "vocal")), fill=factor(stranger))) + geom_bar(position="dodge") + guides(fill=guide_legend(title="Stranger Presence")) + labs(title="Adult Vocalizations by Experimental Condition and Stranger Presence", x = "Experimental Condition", y="number of cases in which adults vocalized")
```

```{r}
adults %>%
  group_by(stranger, vocal) %>%
  filter(adults_speaking == TRUE) %>%
  ggplot(aes(x=factor(stranger), fill=factor(vocal, labels=c("button press", "vocal")))) + geom_bar(position="dodge") + guides(fill=guide_legend(title="Experimental Condition")) + labs(title="Adult Vocalizations by Stranger Presence and Experimental Condition", x = "Stranger Presence", y="number of cases in which adults vocalized")
```